/**
 * MultiTool API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coord } from './coord';
import { MainData } from './mainData';
import { Wind } from './wind';
import { Clouds } from './clouds';
import { Sys } from './sys';


export interface WeatherDto { 
    name?: string | null;
    coord?: Coord;
    main?: MainData;
    wind?: Wind;
    sys?: Sys;
    rain?: any | null;
    snow?: any | null;
    clouds?: Clouds;
}

